version: "3"

services:
  server:
    build: .
    env_file: .env
    volumes:
      - fmgordillo_discord_node_modules:/app/node_modules
      - .:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      IS_DOCKER_ENV: "true"
  db:
    image: mongo
    volumes:
      - fmgordillo_discord_db:/data/db

volumes:
  fmgordillo_discord_db: {}
  fmgordillo_discord_node_modules: {}
